model_params:
  categories:
  - 4
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 3
  - 3
  d_numerical: 5
  d_token: 4
  factor: 32
  n_head: 1
  num_layers: 2
  token_bias: true
training_params:
  beta_decay_factor: 0.7
  beta_max: 0.01
  beta_min: 1.0e-05
